###Test Base_URL
GET http://localhost:3000

# HOST
###Create a Host
POST http://localhost:3000/auth/register
Content-Type: application/json 

{
  "firstName": "Dominic",
  "lastName": "Maina",
  "hostEmail": "dommaina@example.com",
  "hostContact": "0712345678",
  "hostPasswordHash": "dompassword123"
}

# {
#  "firstName": "Jane",
#  "lastName": "Red",
#  "hostEmail": "jred@example.com",
#  "hostContact": "072320220",
#  "hostPasswordHash": "jredpassword123"
# }

### get all hosts
GET http://localhost:3000/auth/hosts/get

### login host
POST http://localhost:3000/auth/loginhost
Content-Type: application/json

{
  "hostEmail": "dommaina@example.com",
  "hostPasswordHash": "dompassword123"
}

### delete host
DELETE http://localhost:3000/auth/hosts/delete/5f32515f-160c-43aa-ad29-80edb4e77075

# ROOMS
### Get all rooms
GET http://localhost:3000/auth/rooms/getall

###create a room
POST http://localhost:3000/auth/rooms/create
Content-Type: application/json

{
  "roomNumber": "8B",
  "roomDescription": "Studio apartment: one bathroom, one bedroom, one dinning room, balcony, dinner and breakfast included",
  "address": "Pamki Building, Kimathi way Nyeri down town",
  "maxGuest": 2,
  "pricePerNight": "2000.00"
}

{
  "roomNumber": "1A",
  "roomDescription": "Bedsitter: one bathroom, one bed, dinner and breakfast included",
  "address": "Pamki Building, Kimathi way Nyeri down town",
  "maxGuest": 2,
  "pricePerNight": "1500.00"
}

###get room by num
GET http://localhost:3000/auth/room/8B

###update room by num
PATCH http://localhost:3000/auth/roomupdate/7B
Content-Type: application/json

{
  "roomstatus": "booked"
}

###get room by guest contact
GET http://localhost:3000/auth/room/roombycontact/0795063598

###get vacant rooms
GET http://localhost:3000/rooms/vacantrooms

###get booked rooms
GET http://localhost:3000/rooms/bookedrooms

###get occupied rooms 
GET http://localhost:3000/rooms/occupiedrooms

###delete room by number
DELETE http://localhost:3000/auth/rooms/roomdelete/8B

# GUESTS
### Get all guests
GET http://localhost:3000/auth/guests

### Create a guest
POST http://localhost:3000/auth/guest/register
Content-Type: application/json

{
  "guestFirstName": "Dom",
  "guestLastName": "Maish",
  "guestContact": "0700000000",
  "guestEmail": "gachaudominic@gmail.com",
  "guestPassword": "dom@123"
}
# {
#   "guestFirstName": "John",
#   "guestLastName": "Kiai",
#   "guestContact": "0795063598",
#   "guestEmail": "johnkiai@example.com",
#   "guestPassword": "jkiai@123"
# }

# {
#   "guestFirstName": "Mitch",
#   "guestLastName": "Nduta",
#   "guestContact": "0725638931",
#   "guestEmail": "mnduta@example.com",
#   "guestPassword": "mnduta@123"

# },
# {
#   "guestFirstName": "John",
#   "guestLastName": "Kiamba",
#   "guestContact": "0747892890",
#   "guestEmail": "johnkiamba@example.com",
#   "guestPassword": "jkiamba@123"
# }

### login guest
POST http://localhost:3000/auth/guest/login
Content-Type: application/json

{
  "guestContact": "0795063598"
}

### get guest by id
GET http://localhost:3000/auth/guest/guestbyid/ee6e1b75-edb1-46dd-9c57-ae8bbcc40f07

### get guest by contact
GET http://localhost:3000/auth/guest/guestbycontact/0725638931

### get guest by roomnum
GET http://localhost:3000/auth/guest/guestbyroomnum/5A

### update guest by contact
PATCH  http://localhost:3000/auth/guest/updateguest/0725638931
Content-Type: application/json

{
  "guestlastName": "Flair"
}

### delete guest
DELETE http://localhost:3000/auth/guest/deleteguest/0722664404


# BOOKINGS
### create booking
POST http://localhost:3000/booking
Content-Type: application/json

{
  "bookingRoomNumber": "4A",
  "bookingGuestId": "8ad7d34d-a9e0-42c5-99dc-761b736c8e93",
  "checkinDate": "2026-07-16",
  "checkoutDate": "2026-07-18",
  "guestCount": 1,
  "totalAmount": "4500.00",
  "bookingStatus": "assigned"
}

### get all bookings
GET http://localhost:3000/auth/bookings

### get booking by its ID
GET http://localhost:3000/auth/bookings/bookingbyid/47c4155c-ed32-4cba-860a-05bc4752aeb8

### get booking guestID
GET http://localhost:3000/auth/bookings/bookingbyguestid/2c3e0176-f501-48e1-908c-c52f6f23465c

### get booking guestID
GET http://localhost:3000/auth/bookings/bookingbyguestid/8ad7d34d-a9e0-42c5-99dc-761b736c8e93

### update booking by 
PATCH http://localhost:3000/auth/bookings/updatebyid/47c4155c-ed32-4cba-860a-05bc4752aeb8
Content-Type: application/json

{
  "bookingGuestId": "8ad7d34d-a9e0-42c5-99dc-761b736c8e93",
  "bookingStatus": "assigned"
}

### delete a booking by its ID
DELETE http://localhost:3000/auth/bookings/deletebyid/d566dc72-2208-4152-9c41-1760e4c6b273


# Payments
### create a payment
POST  http://localhost:3000/payments/createpayment
Content-Type: application/json

{
  "paymentBookingId": "c489b4c6-e1de-41c3-aa63-169a376af956",
  "paymentMethod": "cash",
  "paymentStatus": "confirmed"
}

### get all payments
GET http://localhost:3000/auth/payments

### get payment by its id
GET http://localhost:3000/auth/payments/getpaymentbyid/06ce08ec-1067-43e0-af80-2517f32bb401

### get payment by booking id
GET http://localhost:3000/auth/payments/getpaymentbybookingid/c489b4c6-e1de-41c3-aa63-169a376af956

### update payment by its id
PATCH http://localhost:3000/auth/payments/update/e34c95c6-6ee5-42e4-b65c-1a8fdd549603
Content-Type: application/json

{
  "paymentMethod": "MPesa_paybill",
  "paymentStatus": "pending"
}

### delete payment
DELETE  http://localhost:3000/auth/payments/delete/06ce08ec-1067-43e0-af80-2517f32bb401


# REVIEWS
### create a review
POST http://localhost:3000
Content-Type: application/json

{

}

### get all reviews
GET http://localhost:3000/auth/reviews

### get a review by its id
GET http://localhost:3000/auth/reviews/reviewbyid/55c3db54-8f4a-468b-86ef-d89c305d88b6

### get review by room num
GET http://localhost:3000/auth/reviews/reviewbyroomnum/5A

### update a review by its id
PATCH http://localhost:3000/auth/reviews/updatereviewbyid/55c3db54-8f4a-468b-86ef-d89c305d88b6
Content-Type: application/json

{
  "reviewRating": 4
}

### delete a review by its id
DELETE http://localhost:3000


# ROOMS APPROVALS
### create approval
POST http://localhost:3000/auth/approval/create
Content-Type: application/json

{

}

###get all approvals
GET  http://localhost:3000/auth/approvals

### get approval by its id
GET  http://localhost:3000/auth/approvals/approvalbyid/16c50506-4d2c-424d-84f0-0a206fc949ce

### get approval by roomnum
GET  http://localhost:3000/auth/approvals/approvalbyroomnum/5A

### get approval by guest id
GET http://localhost:3000/auth/approvals/approvalbyguestid/a0596df0-8fcf-46e0-9b76-1310cbd751af

### get pending approvals
GET http://localhost:3000/auth/approvals/pending

### get approved approvals
GET http://localhost:3000/auth/approvals/approved

### get rejected approvals
GET http://localhost:3000/auth/approvals/rejected

### update approval by its id
PATCH http://localhost:3000/auth/approvals/update/updatebyid/16c50506-4d2c-424d-84f0-0a206fc949ce
Content-Type: application/json

{
  "roomAprovalStatus": "pending"
}

### update approval by room num
PATCH http://localhost:3000/auth/approvals/update/updatebyroomnum/4A
Content-Type: application/json

{
  "roomAprovalStatus": "rejected"
}

### update by guest id
PATCH http://localhost:3000/auth/approvals/update/updatebyguestid/a0596df0-8fcf-46e0-9b76-1310cbd751af
Content-Type: application/json

{
  "roomAprovalStatus": "approved"
}

### delete approval by its id
DELETE http://localhost:3000/auth/approvals/delete/deletebyid/

###delete approval by room num
DELETE http://localhost:3000/auth/approvals/delete/deletebyroomnum